Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,7 +50,13 @@ jobs:
 
       - name: Deploy to AWS S3
         run: |
-          aws s3 sync ./angular-15-client/dist/out/ s3://springbootangularproject
+          set -e
+          {
+            aws s3 sync ./angular-15-client/dist/out/ s3://springbootangularproject
+          } || {
+            echo "AWS command failed with exit code $?"
+            exit 1
+          }
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
